spring.application.name=restsmartphone

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3303/demodb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:usuario}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:dios1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080